//
//  ProductService.swift
//  1221Test
//
//  Created by Vermut xxx on 15.08.2024.
//

import Foundation

protocol ProductServiceType {
    func get() async throws -> [Product]
}

final class MockProductService: ProductServiceType {
    func get() async throws -> [Product] {
        [
            .init(id: "goods1",
                  name: "сыр Ламбер 500/0 230г",
                  imageName: "goods1",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 4.1,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: .priceHit,
                  saleLabel: 27,
                  basePricePerKilo: 479.9,
                  salePricePerKilo: 349.9),
            .init(id: "goods17",
                  name: "Энергетический Напиток AdrenaIine Rush 0,449л ж/б",
                  imageName: "goods17",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 4.3,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  basePricePerKilo: 519.9,
                  salePricePerKilo: nil),
            .sampleProductInPieces,
            .init(id: "goods2",
                  name: "Дорадо Охлажденная Непотрошеная 300-400г",
                  imageName: "goods2",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 1.8,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: .priceByCard,
                  saleLabel: 15,
                  basePricePerKilo: 649.9,
                  salePricePerKilo: 549.9),
            .init(id: "goods3",
                  name: "Ролл Маленькая Япония 216г",
                  imageName: "goods3",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 3.1,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  basePricePerKilo: 469.9,
                  salePricePerKilo: nil),
            .init(id: "goods4",
                  name: "Огурцы тепличные cадово-огородные",
                  imageName: "goods4",
                  countryOfOrigin: .france,
                  isFavorite: true,
                  rating: 4.3,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: .priceHit,
                  saleLabel: 14,
                  basePricePerKilo: 279.9,
                  salePricePerKilo: 239.9),
            .init(id: "goods5",
                  name: "Манго Кео",
                  imageName: "goods5",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 3.5,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 800,
                  basePricePerUnit: 118.9,
                  salePricePerUnit: nil),
            .init(id: "goods6",
                  name: "Салат Овощной с Крабовыми Палочками",
                  imageName: "goods6",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods9",
                  name: "Салат Овощной с Крабовыми Палочками",
                  imageName: "goods9",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods10",
                  name: "Салат Овощной с Крабовыми Палочками",
                  imageName: "goods10",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods11",
                  name: "Салат Овощной с Крабовыми Палочками",
                  imageName: "goods11",
                  countryOfOrigin: .france,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods12",
                  name: "Салат Овощной с Крабовыми Палочками",
                  imageName: "goods12",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods13",
                  name: "Энергетический Напиток AdrenaIine Rush 0,449л ж/б",
                  imageName: "goods13",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods14",
                  name: "Энергетический Напиток AdrenaIine Rush 0,449л ж/б",
                  imageName: "goods14",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods15",
                  name: "Энергетический Напиток AdrenaIine Rush 0,449л ж/б",
                  imageName: "goods15",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .init(id: "goods16",
                  name: "Огурцы тепличные cадово-огородные",
                  imageName: "goods16",
                  countryOfOrigin: .russia,
                  isFavorite: false,
                  rating: 5.0,
                  reviews: Array(repeating: ProductReview(), count: 19),
                  promoLabel: nil,
                  saleLabel: nil,
                  unitWeightInGrams: 1000,
                  basePricePerUnit: 499.9,
                  salePricePerUnit: nil),
            .sampleProductInGrams
        ]
    }
}
